name: CI
on: [push]
jobs:
  build:
    name: Test build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '14.15'
      - run: yarn install
      - run: yarn build
